//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RiakProtocolBuffers.proto
namespace System.Data.RiakClient
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpbErrorResp")]
  public partial class RpbErrorResp : global::ProtoBuf.IExtensible
  {
    public RpbErrorResp() {}
    
    private byte[] _errmsg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errmsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] errmsg
    {
      get { return _errmsg; }
      set { _errmsg = value; }
    }
    private uint _errcode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"errcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint errcode
    {
      get { return _errcode; }
      set { _errcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpbListKeysReq")]
  public partial class RpbListKeysReq : global::ProtoBuf.IExtensible
  {
    public RpbListKeysReq() {}
    
    private byte[] _bucket;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bucket", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] bucket
    {
      get { return _bucket; }
      set { _bucket = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpbListKeysResp")]
  public partial class RpbListKeysResp : global::ProtoBuf.IExtensible
  {
    public RpbListKeysResp() {}
    
    private readonly global::System.Collections.Generic.List<byte[]> _keys = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(1, Name=@"keys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> keys
    {
      get { return _keys; }
    }
  

    private bool _done = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"done", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool done
    {
      get { return _done; }
      set { _done = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
}