//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RiakProtocolBuffers.proto
namespace System.Data.RiakClient
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpbErrorResp")]
  public partial class RpbErrorResp : global::ProtoBuf.IExtensible
  {
    public RpbErrorResp() {}
    
    private byte[] _errmsg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errmsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] errmsg
    {
      get { return _errmsg; }
      set { _errmsg = value; }
    }
    private uint _errcode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"errcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint errcode
    {
      get { return _errcode; }
      set { _errcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
}